---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: 'ezpublish.dev'
        memory: '3000'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.102
            forwarded_port:
                OCXWTWxlrHtW:
                    host: '5494'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            MKB7PUDaN0Ce:
                source: ./sites/ezpublish53
                target: /var/www/sites/ezpublish53
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                    auto: 'false'
            hioa:
                source: ./sites/hioa
                target: /var/www/sites/hioa
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim
        - git
        - htop
        - build-essential
        - zsh
firewall:
    install: '1'
    rules: null
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: false
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        ezpublish53:
            servername: ezpublish.dev
            serveraliases:
                - admin.ezpublish.dev
            docroot: /var/www/sites/ezpublish53/web
            directoryindex: index.php
            port: '8080'
            setenv:
                - 'ENVIRONMENT dev'
                - 'USE_APC_CLASSLOADER 0'
                - 'APC_CLASSLOADER_PREFIX "ezpublish"'
                - 'USE_HTTP_CACHE 0'
                - 'USE_DEBUGGING 1'
                - 'TRUSTED_PROXIES "127.0.0.1"'
            rewrites:
                - {rewrite_rule: '^/api/[^/]+/v1/ /index_rest.php [L]'}
                - {rewrite_rule: '^/var/([^/]+/)?storage/images(-versioned)?/.* - [L]'}
                - {rewrite_rule: '^/var/([^/]+/)?cache/(texttoimage|public)/.* - [L]'}
                - {rewrite_rule: '^/design/[^/]+/(stylesheets|images|javascript|fonts)/.* - [L]'}
                - {rewrite_rule: '^/share/icons/.* - [L]'}
                - {rewrite_rule: '^/extension/[^/]+/design/[^/]+/(stylesheets|fonts|flash|images|lib|javascripts?)/.* - [L]'}
                - {rewrite_rule: '^/packages/styles/.+/(stylesheets|images|javascript)/[^/]+/.* - [L]'}
                - {rewrite_rule: '^/packages/styles/.+/thumbnail/.* - [L]'}
                - {rewrite_rule: '^/var/storage/packages/.* - [L]'}
                - {rewrite_rule: '^/favicon\.ico - [L]'}
                - {rewrite_rule: '^/robots\.txt - [L]'}
                - {rewrite_rule: '^/w3c/p3p\.xml - [L]'}
                - {rewrite_rule: '^/sitemap\.xml - [L]'}
                - {rewrite_rule: '^/bundles/ - [L]'}
                - {rewrite_rule: '.* /index.php'}
            override:
                - All
            options:
                - FollowSymLinks
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        hioa:
            servername: hioa.dev
            serveraliases:
                - admin.hioa.dev
            docroot: /var/www/sites/hioa/web
            directoryindex: index.php
            port: '8080'
            setenv:
                - 'ENVIRONMENT dev'
                - 'USE_APC_CLASSLOADER 0'
                - 'APC_CLASSLOADER_PREFIX "ezpublish"'
                - 'USE_HTTP_CACHE 0'
                - 'USE_DEBUGGING 1'
                - 'TRUSTED_PROXIES "127.0.0.1"'
            rewrites:
                - {rewrite_rule: '^/api/[^/]+/v1/ /index_rest.php [L]'}
                - {rewrite_rule: '^/var/([^/]+/)?storage/images(-versioned)?/.* - [L]'}
                - {rewrite_rule: '^/var/([^/]+/)?cache/(texttoimage|public)/.* - [L]'}
                - {rewrite_rule: '^/design/[^/]+/(stylesheets|images|javascript|fonts)/.* - [L]'}
                - {rewrite_rule: '^/share/icons/.* - [L]'}
                - {rewrite_rule: '^/extension/[^/]+/design/[^/]+/(stylesheets|fonts|flash|images|lib|javascripts?)/.* - [L]'}
                - {rewrite_rule: '^/packages/styles/.+/(stylesheets|images|javascript)/[^/]+/.* - [L]'}
                - {rewrite_rule: '^/packages/styles/.+/thumbnail/.* - [L]'}
                - {rewrite_rule: '^/var/storage/packages/.* - [L]'}
                - {rewrite_rule: '^/favicon\.ico - [L]'}
                - {rewrite_rule: '^/robots\.txt - [L]'}
                - {rewrite_rule: '^/w3c/p3p\.xml - [L]'}
                - {rewrite_rule: '^/sitemap\.xml - [L]'}
                - {rewrite_rule: '^/bundles/ - [L]'}
                - {rewrite_rule: '.* /index.php'}
            override:
                - All
            options:
                - FollowSymLinks
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
mysql:
    install: '1'
    root_password: root
    adminer: 0
    databases:
        ezpublish:
            grant:
                - ALL
            name: ezpublish
            host: localhost
            user: ezpublish
            password: ezpublish
        hioa:
            grant:
                - ALL
            name: hioa
            host: localhost
            user: hioa
            password: hioa
            sql_file: ./dist/hioa.sql
php:
    install: '1'
    version: '54'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
            - imagick
            - mbstring
            - mysql
            - xsl
        pear:
            - Crypt_GPG
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Oslo
    mod_php: '1'
varnish:
    install: '0'
    varnish_listen_port: '80'
    varnish_storage_size: '1G'
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
ruby:
    install: '1'
    versions:
        PyYzmum73crk:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        Szt9U9bS1GHY:
            version: ''
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
elastic_search:
    install: '0'
    settings:
        java_install: true
        autoupgrade: true
